# Load package
library(tidyverse)

# Read-in data
ny_census <- read_csv('ny_census.csv')
ny_census_arcgis <- read_csv('ny_census_arcgis.csv')
ny_la_census <- read_csv('ny_la_census.csv')
ny_dc_census <- read_csv('ny_dc_census.csv')

################################################## Transmute NY CENSUS
ny_census_perc <- ny_census %>%
  transmute(
    GEOID,
    pop,
    pop_dens,
    race_white = race_white / pop,
    race_minority = race_minority / pop,
    female = female / pop,
    age_genz = age_genz / pop,
    age_millenial = age_millenial / pop,
    age_genx = age_genx / pop,
    age_boomer = age_boomer / pop,
    age_retiree = age_retiree / pop,
    divsep = divsep / pop,
    widowed = widowed / pop,
    median_age,
    not_us_citizen = not_us_citizen / pop,
    median_earnings,
    trav_cars = trav_cars / pop,
    trav_trans = trav_trans / pop,
    trav_motorcycle = trav_motorcycle / pop,
    trav_bike = trav_bike / pop,
    trav_walk = trav_walk / pop,
    trav_home = trav_home / pop,
    edu_lowedu = edu_lowedu / pop,
    edu_hsged = edu_hsged / pop,
    edu_bs = edu_bs / pop,
    edu_grad = edu_grad / pop,
    unemp = unemp / pop,
    below_pov = below_pov / pop,
    City,
    Borough,
    Class,
    CasualtiesPerPop,
    CasualtiesPerPopDens,
    TotalInjuries,
    TotalDeaths,
    Collisions,
    CasualtiesCount,
    PedeCasualtiesCount
    )
# write.csv(ny_census_perc, 'ny_census_perc.csv', row.names = FALSE)

################################################## Transmute NY CENSUS & ROAD CONDITION
ny_census_arcgis_perc <- ny_census_arcgis %>%
  transmute(
    GEOID,
    pop,
    pop_dens,
    race_white = race_white / pop,
    race_minority = race_minority / pop,
    female = female / pop,
    age_genz = age_genz / pop,
    age_millenial = age_millenial / pop,
    age_genx = age_genx / pop,
    age_boomer = age_boomer / pop,
    age_retiree = age_retiree / pop,
    divsep = divsep / pop,
    widowed = widowed / pop,
    median_age,
    not_us_citizen = not_us_citizen / pop,
    median_earnings,
    trav_cars = trav_cars / pop,
    trav_trans = trav_trans / pop,
    trav_motorcycle = trav_motorcycle / pop,
    trav_bike = trav_bike / pop,
    trav_walk = trav_walk / pop,
    trav_home = trav_home / pop,
    edu_lowedu = edu_lowedu / pop,
    edu_hsged = edu_hsged / pop,
    edu_bs = edu_bs / pop,
    edu_grad = edu_grad / pop,
    unemp = unemp / pop,
    below_pov = below_pov / pop,
    City,
    Borough,
    Class,
    CasualtiesPerPop,
    CasualtiesPerPopDens,
    TotalInjuries,
    TotalDeaths,
    Collisions,
    CasualtiesCount,
    PedeCasualtiesCount,
    road_maxspeed,
    road_meanspeed,
    road_maxlength,
    road_minlength,
    road_meanlength,
    road_totlanes,
    road_maxlanes,
    road_iri,
    road_bumps,
    road_aadt,
    road_sumlength,
    road_pci,
    road_pavewidth,
    road_vc,
    road_q
  )
# write.csv(ny_census_arcgis_perc, 'ny_census_arcgis_perc.csv', row.names = FALSE)

################################################## Transmute NY-LA CENSUS
ny_la_census_perc <- ny_la_census %>%
  transmute(
    GEOID,
    pop,
    pop_dens,
    race_white = race_white / pop,
    race_minority = race_minority / pop,
    female = female / pop,
    age_genz = age_genz / pop,
    age_millenial = age_millenial / pop,
    age_genx = age_genx / pop,
    age_boomer = age_boomer / pop,
    age_retiree = age_retiree / pop,
    divsep = divsep / pop,
    widowed = widowed / pop,
    median_age,
    not_us_citizen = not_us_citizen / pop,
    median_earnings,
    trav_cars = trav_cars / pop,
    trav_trans = trav_trans / pop,
    trav_motorcycle = trav_motorcycle / pop,
    trav_bike = trav_bike / pop,
    trav_walk = trav_walk / pop,
    trav_home = trav_home / pop,
    edu_lowedu = edu_lowedu / pop,
    edu_hsged = edu_hsged / pop,
    edu_bs = edu_bs / pop,
    edu_grad = edu_grad / pop,
    unemp = unemp / pop,
    below_pov = below_pov / pop,
    City,
    Borough,
    Class,
    CasualtiesPerPop,
    CasualtiesPerPopDens,
    TotalInjuries,
    TotalDeaths,
    Collisions,
    CasualtiesCount,
    PedeCasualtiesCount
  )
# write.csv(ny_la_census_perc, 'ny_la_census_perc.csv', row.names = FALSE)

################################################## Transmute NY-DC CENSUS
ny_dc_census_perc <- ny_dc_census %>%
  transmute(
    GEOID,
    pop,
    pop_dens,
    race_white = race_white / pop,
    race_minority = race_minority / pop,
    female = female / pop,
    age_genz = age_genz / pop,
    age_millenial = age_millenial / pop,
    age_genx = age_genx / pop,
    age_boomer = age_boomer / pop,
    age_retiree = age_retiree / pop,
    divsep = divsep / pop,
    widowed = widowed / pop,
    median_age,
    not_us_citizen = not_us_citizen / pop,
    median_earnings,
    trav_cars = trav_cars / pop,
    trav_trans = trav_trans / pop,
    trav_motorcycle = trav_motorcycle / pop,
    trav_bike = trav_bike / pop,
    trav_walk = trav_walk / pop,
    trav_home = trav_home / pop,
    edu_lowedu = edu_lowedu / pop,
    edu_hsged = edu_hsged / pop,
    edu_bs = edu_bs / pop,
    edu_grad = edu_grad / pop,
    unemp = unemp / pop,
    below_pov = below_pov / pop,
    City,
    Borough,
    Class,
    CasualtiesPerPop,
    CasualtiesPerPopDens,
    TotalInjuries,
    TotalDeaths,
    Collisions,
    CasualtiesCount,
    PedeCasualtiesCount
  )
# write.csv(ny_dc_census_perc, 'ny_dc_census_perc.csv', row.names = FALSE)
